name: Build and Deploy

on:
  push:
    paths:
      - 'skater_backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'

    - name: Grant execute permission for gradlew
      run: chmod +x ./skater_backend/gradlew

    - name: Build with Gradle
      run: ./skater_backend/gradlew build

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: ./skater_backend/build/libs/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: build-artifact
        path: ./build

    - name: Copy files via SSH
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: "./build/*.jar"
        target: "/home/ec2-user/app.jar"

    - name: Execute remote command
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          sudo systemctl stop myapp
          sudo mv /home/ec2-user/app.jar /opt/myapp/app.jar
          sudo systemctl start myapp